name: salt-project
recipe: drupal8
config:
  webroot: web
  conf:
    php: config/php.ini
services:
  d7db:
    type: mariadb
    creds:
      user: drupal7db
      password: drupal7db
      database: drupal7db
