<?php

/**
* Implements hook_preprocess_comment
*/
function saltproject_preprocess_comment(&$variables) {
  $comment = $variables['elements']['#comment'];
  $account = $comment->getOwner();
  $username = [
    '#theme' => 'username',
    '#account' => $account,
  ];

  $variables['author'] = \Drupal::service('renderer')->render($username);
  $variables['submitted'] = t('@username', ['@username' => $variables['author']]);
}