id: article_csv_import
label: Import articles
migration_groups:
  - ACME import

source:
  plugin: csv
  # Full path to the file.
  path: "public://migration/csv/articles.csv"
  # Column delimiter. Comma (,) by default.
  delimiter: ","
  # Field enclosure. Double quotation marks (") by default.
  enclosure: '"'
  # The number of rows at the beginning which are not data.
  header_row_count: 1
  # The column(s) to use as a key. Each column specified will
  # create an index in the migration table and too many columns
  # may throw an index size error.
  keys:
    - id
  # Here we identify the columns of interest in the source file.
  # Each numeric key is the 0-based index of the column.
  # For each column, the key below is the field name assigned to
  # the data on import, to be used in field mappings below.
  # The value is a user-friendly string for display by the
  # migration UI.
  column_names:
    0:
      id: "Unique Id"
    1:
      title: "Title"
    2:
      body: "Post body"
process:
  title: title
  body: body
  type:
    plugin: default_value
    default_value: article

destination:
  plugin: entity:node
